name: Cub3D CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libx11-dev libxext-dev libbsd-dev
    
    - name: Build project
      run: |
        make clean
        make
    
    - name: Test compilation
      run: |
        test -f cub3d
        echo "✅ Main executable built successfully"
    
    - name: Test bonus compilation
      run: |
        make bonus
        test -f cub3D_bonus
        echo "✅ Bonus executable built successfully"
    
    - name: Test with sample map
      run: |
        timeout 5s ./cub3d maps/good/test_map.cub || true
        echo "✅ Game runs without immediate crashes"
    
    - name: Clean up
      run: make fclean
